### PR TITLE
add api get endpoint orders by seller id

### PR DESCRIPTION
**Pull request by cnfrancis**
I used `seller_id := 1`.
Looking at the database there are 5 orders with at least one product with `seller_id := 1`
ordersbyseller

### CODE REVIEW

**Comment by emrb9** [comment]
great work!

**Review by emrb9 — APPROVED** [review]
great work!

**Comment by cnfrancis** [comment]
> 
its all about the lazyness

**Comment by cnfrancis** [comment]
> great work!

i liked the way you formatted the backend and the comments so I followed it

**Pull request merged**
